# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-DBIProfile
version:      0.05
version_from: DBIProfile.pm
installdirs:  site
requires:
    CGI::Application:              4
    Data::JavaScript:              0
    DBI:                           1.49
    HTML::Template:                2.6
    IO::Scalar:                    0
    Symbol:                        0
    Test::More:                    0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
